In [1]:
import numpy as np

#### Vectorization

In [28]:
a = np.array([0, 1, 2])
print(a)

[0 1 2]


In [11]:
# WEEK 2 - VECTORIZATION
import time

dim = 1000000
a = np.random.rand(dim)
b = np.random.rand(dim)


# vectorized
tic = time.time()
c = np.dot(a, b)
toc = time.time()
print(c, ' - non-vectorized: '+ str((toc - tic)*1000))


#for loop
c = 0
tic = time.time()
for i in range(dim):
    c += a[i] * b[i]
toc = time.time()
print(c, ' - non-vectorized: '+ str((toc - tic)*1000))

249900.87279515096  - non-vectorized: 4.982471466064453
249900.87279514674  - non-vectorized: 567.1525001525879


In [24]:
d = np.zeros((3, 1))

In [14]:
#broadcasting
A = np.array([
    [56.0, 0.0,  4.4,  68.0],
    [1.2 , 104.0, 52.0, 8.0],
    [1.8 , 135.0, 99.0, 0.9]
])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [15]:
cal = A.sum(axis=0) #sum vertically
print(cal)

[ 59.  239.  155.4  76.9]


In [23]:
percentage = 100*A/(cal.reshape(1, 4))
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [26]:
print(d + 100)

[[100.]
 [100.]
 [100.]]


In [44]:
# random gaussian vector
e = np.random.randn(5) # rank 1 matrix
print(e)
e_reshape = e.reshape((5, 1))
print(e_reshape)

[ 1.07758448 -0.27295633 -0.61618625 -1.64054072  1.8205573 ]
[[ 1.07758448]
 [-0.27295633]
 [-0.61618625]
 [-1.64054072]
 [ 1.8205573 ]]


In [45]:
try:
    assert(e.shape == (5,))
    print(True)
except AssertionError:
    print(False)
   

True


In [47]:
#quiz computations
a = np.array([[2,1],[1,3]])
np.dot(a, a)

array([[ 5,  5],
       [ 5, 10]])

In [50]:
a = np.array([   #2x2
    [1, 1],
    [1, (-1)]
])

b = np.array([
    [2],        #2x1 --> 2x2
    [3]
])


c = a + b  # [[3, 3],[4, 2]]
print(c)

[[3 3]
 [4 2]]
