<a href="https://colab.research.google.com/github/mehrshad-sdtn/DeepLearning/blob/master/DL-PyTorch/operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [6]:
print(torch.cuda.is_available())
print(torch.randn(2, 2))

False
tensor([[-0.6561,  1.8127],
        [-0.2711,  0.5104]])


In [11]:
x = torch.zeros(3, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [18]:
cpu_tensor = torch.rand(2)
cpu_tensor.device

device(type='cpu')

In [37]:
## operations
a = torch.rand(1, 2)
b = torch.rand(1, 2)
c = a + b

## broadcast
a2 = a * torch.tensor(2)
print(a2)
## log
d = torch.rand(2, 2)
logd = d.log2()
print(logd)

tensor([[1.2721, 0.6617]])
tensor([[-0.9788, -0.4338],
        [-0.4546, -2.5006]])


In [23]:
## reshaping tensors
flat_tensor = torch.rand(784)
viewed_tensor = flat_tensor.view(1, 28, 28)
print(viewed_tensor.shape)
reshaped_tensor = flat_tensor.reshape(1, 28, 28)
print(reshaped_tensor.shape)

torch.Size([1, 28, 28])
torch.Size([1, 28, 28])


In [25]:
hwc_tensor = torch.rand(640, 480, 3)
chw_tensor = hwc_tensor.permute(2, 0, 1)
chw_tensor.shape

torch.Size([3, 640, 480])